### ISSUE TITLE
YiiBooster requires PHP version? How do I need to make it support PHP 5.2.0?

### ISSUE THREAD

**Issue by supgeek-rod** [clevertech/YiiBooster#1000]
I want to know what the use is not supported by PHP5.2 new features?

help me  - _ - )

**Comment by hijarian** [comment]
We do not use the short array syntax and closures.
Most possibly you'll encounter anonymous functions in some complex widgets so, I personally guess that you'll not be able to use YiiBooster in PHP 5.2 environment.

Apart from that, hard to remember features specific for PHP 5.3, which we use. It's unusual to work with such ancient versions of PHP in 2015.

_what a failget_

**Comment by supgeek-rod** [comment]
waiting for news of victory

**Comment by supgeek-rod** [comment]
I think I finished the work, https://github.com/supgeek-rod/YiiBooster/tree/php5.2

**Comment by hijarian** [comment]
Absolutely minimal requirement for YiiBooster is PHP 5.3
