### ISSUE TITLE
TbSwitch > switchGroup > onText & ofText can not be set

### ISSUE THREAD

**Issue by bandpay** [clevertech/YiiBooster#1003]
Hi,
It seems that $this->options doesn't carry the onText/offText to the widget.

in TbSwitch.ph line 77

$config = CJavaScript::encode($this->options); 

Thanks
Sincerely
Babak

**Comment by amrbedair** [comment]
I tested it ... it is working 
    <?php echo $form->switchGroup($model, 'active', ['widgetOptions' => ['options' => ['onText' => 'X', 'offText' => 'Z'] ] ]); ?>

plz confirm you still face the problem

**Comment by bandpay** [comment]
No Problem, My bad :)
