### ISSUE TITLE
TbActiveForm radio BUG for Bootstrap3.2

### ISSUE THREAD

**Issue by supgeek-rod** [clevertech/YiiBooster#1007]
![2015-02-11 11 17 05](https://cloud.githubusercontent.com/assets/5748006/6141380/8f1fc974-b1df-11e4-99a8-3ba6764bc370.png)

**Comment by supgeek-rod** [comment]
![2015-02-11 11 18 16](https://cloud.githubusercontent.com/assets/5748006/6141391/b60fbd28-b1df-11e4-9524-fb3f3ba95623.png)

**Comment by amrbedair** [comment]
fixed
