### ISSUE TITLE
Ajax grid filter not filtering grid when on page greater than 1. Grid paging not being set back to 1

### ISSUE THREAD

**Issue by jackkitley** [clevertech/YiiBooster#1010]
I have a grid with a few pages of data. Ive noticed that when im on a page greater than 1 and if i do a ajax filter on the grid, which sends the params to the model to filter then the grid does not filter on that value that i have selected.

**Comment by jackkitley** [comment]
Please see examples below: 
![screen shot 2015-03-06 at 09 09 25](https://cloud.githubusercontent.com/assets/3243014/6521438/8f2847d0-c3e0-11e4-98c9-d381a767ca48.png)
![screen shot 2015-03-06 at 09 09 07](https://cloud.githubusercontent.com/assets/3243014/6521439/8f28d15a-c3e0-11e4-979c-ba52112df087.png)

**Comment by jackkitley** [comment]
Please see examples below:

![screen shot 2015-03-06 at 09 09 25](https://cloud.githubusercontent.com/assets/3243014/6521461/f0030f22-c3e0-11e4-8ec8-401b393ae38a.png)
![screen shot 2015-03-06 at 09 09 07](https://cloud.githubusercontent.com/assets/3243014/6521462/f006746e-c3e0-11e4-802e-dce03afc06c2.png)

**Comment by amrbedair** [comment]
@jackkitley check your code man! how can this be related to booster!
