### ISSUE TITLE
Double Arrow in Grid - Any Reason Why?

### ISSUE THREAD

**Issue by chodges** [clevertech/YiiBooster#1019]
Hello:

A client of mine asked why there are two arrows in the grid for a sortable column.  And I couldn't come up with a good explanation so maybe you can tell me why.

![screen shot 2015-03-26 at 10 20 58 am](https://cloud.githubusercontent.com/assets/197811/6852433/d3fe7822-d3a1-11e4-8e2d-20e0894f75a1.png)

**Comment by Wiseon3** [comment]
Hi,

The second arrow (black one in the right) appears only on mouse over to show the direction in which you will sort if you click the column header.

**Comment by chodges** [comment]
Thanks!  Makes sense.
