### ISSUE TITLE
Do you have some plan update this project to yii2 framework?

### ISSUE THREAD

**Issue by FavorMylikes** [clevertech/YiiBooster#1036]
Thank you guys,It's very helpful to me.Recently I want to start a new project with Yii 2 framework,and I found many plugin about bootstrap.But there no one is easier than this.Do you have some plan update this project to Yii 2 framework?I wanna join it and write some code to help you.

**Comment by amrbedair** [comment]
unfortunately no plan for this ... at this point of time ... we do not have any free dedicated developer for this project ...I hope we can do soon 

have you tried https://github.com/2amigos

**Comment by hijarian** [comment]
@FavorMylikes I'll be short: yes, we do have plans. Anticipating the next question: no, we don't know when. ;)
