### ISSUE TITLE
Can you, please, update requirement for yii as '>=1.1.15'

### ISSUE THREAD

**Issue by fazliddin** [clevertech/YiiBooster#1037]
So far I have used yiibooster with yii-1.1.16 version and it works, but recently I tried to update to 1.1.17 version and could not do this due to yiibooster requirement.

**Comment by PrplHaz4** [comment]
It looks like this was done in this commit: 5d2ec0ff49b1656ffe9b4ee44ca45c57c9f6e96c

Are there things that were explicitly broken in YiiBooster when used with 1.1.16+, or has it just not been tested against these versions of Yii?

**Comment by fazliddin** [comment]
I am now using latest yii-booster with Yii 1.1.17. My whole admin interface is build with yii-booster, and there is no problem.

**Comment by PrplHaz4** [comment]
@hijarian any idea if changing the requirement to ">=1.1.15" is the right approach?

For my system, I don't load yii via composer (to allow swapping it out without large file copies) but I'm not sure that is a valid requirement for a library like this.
