### ISSUE TITLE
TbActiveForm: Object of class XXX could not be converted to int

### ISSUE THREAD

**Issue by kachar** [clevertech/YiiBooster#182]
Hi,

There is a problem with `bootstrap.widgets.TbActiveForm` when trying to use Giix Crud Generator with YiiBooster.

Giix generates the following code to get the relations:

```
<label><?php echo GxHtml::encode($model->getRelationLabel('acceptanceLists')); ?></label>
<?php 
echo $form->checkBoxList($model, 'acceptanceLists', GxHtml::encodeEx(GxHtml::listDataEx(AcceptanceLists::model()->findAllAttributes(null, true)), false, true)); 
?>
```

The problem comes from a check  at `protected/extensions/bootstrap/widgets/TbActiveForm.php(Line 511)` 

function `inputsList()`

```
$checked = !is_array($select) && !strcmp($value, $select) || is_array($select) && in_array($value, $select);
```

When `in_array`  tries to cast `AcceptanceLists` object to int an PHP Notice is thrown.

Any suggestions are welcome.

Thanks

**Comment by grussi** [comment]
I GOT THIS! Oh god, after many hours of debugging, this is the solucion I got to make it work.
On the actionUpdate, i placed this before the render function:
$unidades = array();
foreach($model->unidades as $unidade) {
        $unidades[] = $unidade->id;
}
$model->unidades = $unidades;
The thing is: The checkBoxList of yiiBooster needs a array type, and it cannot convert a class type into an array. So this worked perfectly and kept de yiiBooster appearence.
