### ISSUE TITLE
When using with append or prepend icon, datepickerRow does not put value of date in textbox

### ISSUE THREAD

**Issue by anilkonsal** [clevertech/YiiBooster#337]
![Screen Shot 2013-02-20 at 5 57 28 PM](https://f.cloud.github.com/assets/2535407/175790/01bf037e-7b59-11e2-8416-996cb817fef7.jpg)
When using with append or prepend datepickerRow does not put value of date in textbox. I tried adding array('prepend'=>'<i class="icon-calendar"></i>') in the options, bit it stops filling the date immediately. Works fine when this is removed.

**Comment by amrbedair** [comment]
user not responding for a year!
