### ISSUE TITLE
TbEditableField with `date` type does not support locales

### ISSUE THREAD

**Issue by hijarian** [clevertech/YiiBooster#689]
This invocation:

``` php
$this->widget(
    'bootstrap.widgets.TbEditableField',
    array(
        'type' => 'date',
        'model' => $model,
        'attribute' => 'someDateAttribute',
        'url' => $endpoint, //url for submit data
        'options' => array(
            'datepicker' => array(
                'language' => 'ru'
            )
        )
    )
);
```

makes editable field with datepicker in English, not Russian.

Language file for Russian datepicker is being loaded, but editable field does not use it.

It has something to do with https://github.com/vitalets/x-editable/blob/master/src/inputs/date/date.js#L32

Making `x-editable` package dependent on the `datepicker` package (so it'll load after our datepicker) and registering the script 

``` javascript
if ($.fn.datepicker.dates) {
   $.fn.bdatepicker.dates = $.fn.datepicker.dates;
}
```

do not change anything.

Locales in the `TbDatePicker` itself work as expected.

**Comment by islopma** [comment]
I'm having a similar issue using the master branch. When I use the Editable Field with type "date" as described in http://yiibooster.clevertech.biz/widgets/editable/view/field.html#example-date-field I get the following errors:

Uncaught TypeError: Cannot set property 'ru' of undefined
Uncaught TypeError: Cannot read property 'daysShort' of undefined

In the link there is a link to this issue, although there it seems to be fixed (datepicker loads in russian).
