### ISSUE TITLE
datepicker localization 

### ISSUE THREAD

**Issue by gureedo** [clevertech/YiiBooster#70]
At this moment TbDatepicker widget code doesn't contains any references for registering localization file via asset manager. Even if i add it, it not works, because it seems that localization taken from https://github.com/eternicode/bootstrap-datepicker and all other datepicker code taken from http://www.eyecon.ro/bootstrap-datepicker/
So localization is not compatible with main datepicker code.

**Comment by mohammad-eghlima** [comment]
Hi
We are using Yii 1.1.16 and Yiibooster 4.0.1.
We need to apply this format for all datepickers: yyyy-mm-dd

but it seems there is no way to handle it just by specifying format component in main.php config file like this:
'format' => array(  // config/main.php
        'datetimeFormat' => "yyyy-M-dd h:m:s",
        'dateFormat' => "yyyy-M-dd"
), 

I found something in TbDatePicker::init, if we add this code in init method, this class will be able to read `format` from global configuration:

if (isset(\Yii::app()->format) && isset(\Yii::app()->format->dateFormat)) {
	$this->options['format'] = \Yii::app()->format->dateFormat;
}

Is it good practice? and if it is have you any plan to do it in your next versions?
Or there is already a configuration in yii, compatible with booster that i have missed?

already i handle this by adding these lines to main layout file of the project:
\Yii::app()->clientScript->registerScript("jquery-date-fix",
    "$.fn.datepicker.defaults.format = 'yyyy-mm-dd';
     $.fn.datepicker.defaults.autoclose = true;",
    \CClientScript::POS_BEGIN);
?>

thank you in advance
