### ISSUE TITLE
TbButtonColumn throwing erros in IE 8

### ISSUE THREAD

**Issue by manquer** [clevertech/YiiBooster#789]
TbButtonColumn in IE 8 throws errors and makes the icons unusable ( error is thrown on hover )

````
Line: 589
Error: Array or arguments object expected
````
on jquery.js

I have tested exact same GridView & Button Column with CButtonColumn, and CGridView, this happens with only in ````TbButtonColumn```` while using either custom or default templates 

Version :2.1.1 & 3.0.1

**Comment by hijarian** [comment]
I'm sorry, but it's upstream problem. And old one, too.
