### ISSUE TITLE
TbHtml::activeCheckBoxList check $htmlOptions['uncheckValue'] not like as CHtml::activeCheckBoxList

### ISSUE THREAD

**Issue by Rey8d01** [clevertech/YiiBooster#917]
Hi.

In method TbHtml::activeCheckBoxList $uncheckValue - always is rendering checkBox hidden input for send to server.

$uncheckValue = isset($htmlOptions['uncheckValue']) ? TbArray::popValue('uncheckValue', $htmlOptions) : '';

even if $uncheckValue = '' then isset($uncheckValue) === true and 
$hidden = isset($uncheckValue) ? parent::hiddenField($name, $uncheckValue, $hiddenOptions) : '';
always insert hidden field.

in CHtml::activeCheckBoxList is true checker.

ps: sorry my english.

**Comment by IStranger** [comment]
Similar bug discovered in method <b>TbHtml::activeRadioButtonList</b>. 
Error in case: <b>$htmlOptions = ['uncheckValue' => null]</b>.
