### ISSUE TITLE
Yii 4.0.1 - Editable in grid on bringing in data via ajax load not working.

### ISSUE THREAD

**Issue by jackkitley** [clevertech/YiiBooster#949]
I have a editable grid with columns that can be changed with a popup editable. On default load of data in the grid i can edit the data and the striped underline will show.

When there is no data by default and you bring data into the grid there is a solid blue line and you cant click the value to edit it in the editable popup.

I remember this being an issue that was fixed in an older version when you had to re-register the javascript.

Thanks
![screen shot 2014-09-15 at 12 52 21 pm](https://cloud.githubusercontent.com/assets/3243014/4270189/f03fd5f2-3cc6-11e4-9748-5c1da9b2bf29.png)
![screen shot 2014-09-15 at 12 51 45 pm](https://cloud.githubusercontent.com/assets/3243014/4270188/f03c5b5c-3cc6-11e4-9b5a-86e12ba583dc.png)

**Comment by jackkitley** [comment]
Has this been actioned on? quite an annoying bug. thanks

**Comment by jackkitley** [comment]
@lisps  @kongoon  @marsuboss  @rlucian Hi Guys, sorry to bother but im not sure how i can temporarily fix this problem. It happens when a grid is populated from no data to have some data and then the grid having the edible feature enabled. Im not sure if its a quick fix and i do understand you are very busy but any assistance would be grateful. Thanks alot

**Comment by jackkitley** [comment]
@hijarian  Hi Mark, was this ticket #954 that recently closed?

**Comment by hijarian** [comment]
@jackkitley I think #954 and #949 (this ticket) are not related. However, you can check out latest master, containing the changes from PR #954 and see for yourself whether the editable correctly instantiates when the grid is being filled with data. If it's not, then this ticket is not closed.
